name: linting, testing, building

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   pipeline:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [18.x]

      steps:
         - uses: actions/checkout@v2

         - name: Set up Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: ${{ matrix.node-version }}

         - name: Cache Node.js modules
           uses: actions/cache@v2
           with:
              path: ~/.npm
              key:
                 ${{ runner.os }}-node-${{ matrix.node-version }}-${{
                 hashFiles('**/package-lock.json') }}
              restore-keys: |
                 ${{ runner.os }}-node-${{ matrix.node-version }}-

         - name: Install modules
           run: npm ci

         - name: Build production project
           run: npm run build:prod
           if: success() || failure()

         - name: Lint TypeScript
           run: npm run lint:ts
           if: success() || failure()

         - name: Lint CSS
           run: npm run lint:scss
           if: success() || failure()

         - name: Run unit tests
           run: npm run test:unit
           if: success() || failure()

         - name: Build Storybook
           run: npm run storybook:build
           if: success() || failure()

         - name: Screenshot testing
           run: npm run test:ui:ci
           if: success() || failure()
